### ISSUE TITLE
How can I use this to extract the data from the hourglass-export.json file?

### ISSUE THREAD

**Issue by djismgaming** [AurelienMarchand/RelWis-Hourglass#1]
I have the hourglass-export.json file. Would like to find a way to export data to a more usable state if possible. Is there any way with this project or another that you may know?

Thanks in advance.

I cloned the code to a nginx/php server and got the screen with three buttons:

Dump File to Console

Import File to SQLite

Create Phone Contact List

**Comment by AurelienMarchand** [comment]
I created this for my own purposes and wasn't expecting anyone else to use it!

The index.php is not the best way to run the program. It's best to do it from a terminal and launch terminal.php. From there, type HELP to get a list of commands to run.

Typically, I do in order: 
IMPORT
REPORT
TOTALS
QUIT

This will import the file **hourglass-export.json** into the DB, create a CSV that I manually adjust for presentation and finally dump to the screen the running pioneer hour totals which I also add to the adjusted CSV.

There is room for improvement of course. If you are a developer, feel free to clone the repo and get inspiration for your own data conversion. 

All the best!

**Comment by djismgaming** [comment]
I see now! Thanks! I don't consider myself a developer. I do love docker (what I use for my docker/plex/foldforcovid media server) and the webserver to run this using linuxserver/nginx.

I'll definitely explore this! Thanks!

![image](https://user-images.githubusercontent.com/25346053/82753365-f33f0100-9d92-11ea-8c78-f3c0578cd4fc.png)

I'm in! Thanks again 😃
